"""
Django settings for Safeplace project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-q3=+123_-!0of8m5-!v1tpw!uflyp$$zixw!d^66d6a(hgpa@i')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

_allowed_hosts_raw = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver,.railway.app,.vercel.app,.onrender.com')
if _allowed_hosts_raw.strip() == '*':
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(',') if h.strip()]

# Support for Vercel Proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'podcastSafe',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Safeplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'podcastSafe' / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'podcastSafe.context_processors.profile_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'Safeplace.wsgi.application'


# ── Base de données ────────────────────────────────────────────────────────────
# Lire DATABASE_URL depuis l'environnement (ex: variable Heroku/Railway/Supabase)
DATABASE_URL = os.getenv('DATABASE_URL') or os.getenv('SUPABASE_DB_URL')
if DATABASE_URL:
    parsed = urlparse(DATABASE_URL)
    # extra query params (ex: sslmode=require) -> use them when present
    query = {}
    if parsed.query:
        for part in parsed.query.split('&'):
            if '=' in part:
                k, v = part.split('=', 1)
                query[k] = v

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path.lstrip('/'),
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': parsed.hostname,
            'PORT': parsed.port or '5432',
            'OPTIONS': {
                'sslmode': query.get('sslmode', 'require')
            },
        }
    }
elif os.getenv('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME':     config('POSTGRES_DB',       default='safeplace_test'),
            'USER':     config('POSTGRES_USER',     default='test'),
            'PASSWORD': config('POSTGRES_PASSWORD', default='test'),
            'HOST':     config('POSTGRES_HOST',     default='localhost'),
            'PORT':     config('POSTGRES_PORT',     default='5432'),
            'OPTIONS': {'sslmode': 'require'},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ── Validation des mots de passe ───────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ── Internationalisation ───────────────────────────────────────────────────────
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True


# ── Fichiers statiques ─────────────────────────────────────────────────────────
STATIC_URL        = '/static/'
STATIC_ROOT       = BASE_DIR / 'staticfiles'
STATICFILES_DIRS  = [BASE_DIR / 'static']
WHITENOISE_USE_FINDERS = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Stockage media local (VPS Hostinger) ──────────────────────────────────────
MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default':     {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

# Chunks de 5-10 MB — les gros fichiers sont découpés côté dashboard avant envoi
DATA_UPLOAD_MAX_MEMORY_SIZE  = 10 * 1024 * 1024   # 10 MB max par chunk reçu
FILE_UPLOAD_MAX_MEMORY_SIZE  = 10 * 1024 * 1024   # au-delà → fichier temporaire disque
DATA_UPLOAD_MAX_NUMBER_FIELDS = None               # pas de limite sur les champs


# ── URLs principales ───────────────────────────────────────────────────────────
MAIN_SITE_URL    = os.environ.get('MAIN_SITE_URL', 'http://127.0.0.1:8000')
MAIN_API_URL     = os.environ.get('MAIN_API_URL',  'http://127.0.0.1:8000/api/v1/')

DASHBOARD_API_KEY = config('DASHBOARD_API_KEY', default='safeplace_secret_dashboard_key_2026')
DASHBOARD_NETLIFY_URL = os.environ.get('DASHBOARD_NETLIFY_URL', 'https://poetic-torte-67284f.netlify.app')
DASHBOARD_URL = os.environ.get('DASHBOARD_URL', DASHBOARD_NETLIFY_URL)

# Normalize origins for CORS (no path allowed)
def get_origin(url):
    parsed = urlparse(url)
    if parsed.scheme and parsed.netloc:
        return f"{parsed.scheme}://{parsed.netloc}"
    return url.rstrip('/')

DASHBOARD_NETLIFY_ORIGIN = get_origin(DASHBOARD_NETLIFY_URL)
DASHBOARD_ORIGIN = get_origin(DASHBOARD_URL)

# URL publique du site (utilisée pour les redirections Wave après paiement)
# URL publique du site
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

# ── CORS Configuration ───────────────────────────────────────────────────────
# Dashboard protégé par API key — on accepte toutes les origines HTTPS.
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]


# ── Paiements et dons désactivés ───────────────────────────────────────────
# Plus de configuration Stripe / Wave / paiements directs dans ce projet.


# ── Sécurité des cookies & headers HTTP ───────────────────────────────────────
SESSION_COOKIE_SECURE   = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE      = not DEBUG
CSRF_COOKIE_HTTPONLY    = True

# Headers de sécurité
SECURE_CONTENT_TYPE_NOSNIFF     = True
SECURE_BROWSER_XSS_FILTER       = True
X_FRAME_OPTIONS                 = 'DENY'
SECURE_REFERRER_POLICY          = 'strict-origin-when-cross-origin'

# HSTS uniquement en production — Railway gère le SSL au niveau proxy,
# SECURE_SSL_REDIRECT doit rester False sinon le healthcheck interne (HTTP) reçoit un 301
_is_local = any(h in ALLOWED_HOSTS for h in ('localhost', '127.0.0.1'))
if not DEBUG and not _is_local:
    SECURE_HSTS_SECONDS            = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD            = True
    SECURE_SSL_REDIRECT            = False  # Railway termine le SSL au proxy


# ── Dons — coordonnées Mobile Money ───────────────────────────────────────────
DONATION_WAVE_NUMBER   = config('DONATION_WAVE_NUMBER',   default='')
DONATION_WAVE_NAME     = config('DONATION_WAVE_NAME',     default='The SafePlace by K')
DONATION_ORANGE_NUMBER = config('DONATION_ORANGE_NUMBER', default='')
DONATION_ORANGE_NAME   = config('DONATION_ORANGE_NAME',   default='The SafePlace by K')
DONATION_MESSAGE       = config('DONATION_MESSAGE',       default='Don SafePlace')

# ── Auth ───────────────────────────────────────────────────────────────────────
LOGIN_URL          = 'admin:login'
LOGIN_REDIRECT_URL = 'home'


# ── Cache Redis (DB 1 — séparé du broker Celery sur DB 0) ─────────────────────
# Si CACHE_REDIS_URL n'est pas défini, on utilise la mémoire locale (dev/test).
_cache_redis_url = os.environ.get('CACHE_REDIS_URL', '')
if _cache_redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': _cache_redis_url,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'IGNORE_EXCEPTIONS': True,  # si Redis tombe, l'app continue sans cache
                'CONNECTION_POOL_KWARGS': {'max_connections': 50},
            },
            'TIMEOUT': 300,
            'KEY_PREFIX': 'safeplace',
        }
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
    SESSION_CACHE_ALIAS = 'default'
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'safeplace-locmem',
        }
    }

# ── Celery ─────────────────────────────────────────────────────────────────────
# CELERY_BROKER_URL doit être défini dans l'environnement en production
CELERY_BROKER_URL     = config('CELERY_BROKER_URL',    default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT  = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE        = 'UTC'


# ── Email ──────────────────────────────────────────────────────────────────────
EMAIL_BACKEND   = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST      = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT      = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS   = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@safeplace.com')
ADMINS = [('Admin', os.environ.get('ADMIN_EMAIL', ''))] if os.environ.get('ADMIN_EMAIL') else []

# ── Logging ────────────────────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '[{levelname}] {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'ERROR', 'propagate': False},
        'django.request': {'handlers': ['console'], 'level': 'ERROR', 'propagate': False},
    },
}